### ISSUE TITLE
how to start this program again?

### ISSUE THREAD

**Issue by wadabeewadabeedoo** [rerrahkr/ConvFMML#2]
I can't see any .exe in any folder. Not all of us know how to start a program without .exe.

**Comment by rerrahkr** [comment]
~~Would you downloaded BambooTracker-(version number).zip from [Release page](https://github.com/rerrahkr/BambooTracker/releases)? I checked the binary in this.~~

**Comment by rerrahkr** [comment]
@obink The above comment was completely misguided. Sorry for my mistake and late reply.

I checked ConvFMML-v1.1.0.zip (latest release) from [Release page](https://github.com/rerrahkr/ConvFMML/releases), and it contains ConvFMML.exe. Is there a possibility that the program binary have been accidentally moved to a quarantine due to security protection in your computer?

**Comment by rerrahkr** [comment]
Close this issue once it has been abandoned.
